"""提示词库"""
from .prompt_ma_cross import SYSTEM_PROMPT as MA_CROSS_SYSTEM, DECISION_TEMPLATE as MA_CROSS_TEMPLATE
from .prompt_breakout import SYSTEM_PROMPT as BREAKOUT_SYSTEM, DECISION_TEMPLATE as BREAKOUT_TEMPLATE
from .prompt_value import SYSTEM_PROMPT as VALUE_SYSTEM, DECISION_TEMPLATE as VALUE_TEMPLATE
from .prompt_momentum import SYSTEM_PROMPT as MOMENTUM_SYSTEM, DECISION_TEMPLATE as MOMENTUM_TEMPLATE
from .prompt_sentiment import SYSTEM_PROMPT as SENTIMENT_SYSTEM, DECISION_TEMPLATE as SENTIMENT_TEMPLATE

__all__ = [
    'MA_CROSS_SYSTEM',
    'MA_CROSS_TEMPLATE',
    'BREAKOUT_SYSTEM',
    'BREAKOUT_TEMPLATE',
    'VALUE_SYSTEM',
    'VALUE_TEMPLATE',
    'MOMENTUM_SYSTEM',
    'MOMENTUM_TEMPLATE',
    'SENTIMENT_SYSTEM',
    'SENTIMENT_TEMPLATE',
]
